#version 450

struct Particle
{
	vec3 pos;
	bool valid;
	int gridCellIndex;
};

struct GridCell
{
	int count;
	int offset;
};

layout(binding = 0) buffer FluidUniform
{
	int particlesCount;
	float gridCellSize;
	ivec3 gridDimentions;
	vec3 gridSize;
} Fluid;

layout(binding = 1) buffer ParticlesStorage
{
	Particle particles[];
} Particles;

layout(binding = 2) buffer ParticlesStorageCopy
{
	Particle particles[];
} ParticlesCopy;

layout(binding = 3) buffer GridStorage
{
	GridCell cells[];
} Grid;

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

ivec3 particleGridPos(vec3 pos)
{
	vec3 shiftFromCenter = Fluid.gridDimentions * Fluid.gridCellSize / 2;
	vec3 particlePosInGrid = (pos + shiftFromCenter) / Fluid.gridCellSize;
	ivec3 partGridPos = ivec3(floor(particlePosInGrid));
	return partGridPos;
}

int particleGridIndex(ivec3 partGridPos)
{
	int partGridIndex = partGridPos.x
		+ partGridPos.y * Fluid.gridDimentions.x
		+ partGridPos.z * Fluid.gridDimentions.x * Fluid.gridDimentions.y;
	return partGridIndex;
}

bool gridPosValidation(ivec3 particleGridPos)
{
	if (particleGridPos.x < 0 || particleGridPos.x >= Fluid.gridDimentions.x)
	{
		return false;
	}
	if (particleGridPos.y < 0 || particleGridPos.y >= Fluid.gridDimentions.y)
	{
		return false;
	}
	if (particleGridPos.z < 0 || particleGridPos.z >= Fluid.gridDimentions.z)
	{
		return false;
	}
	return true;
}

void clearGrid()
{
    uint index = gl_GlobalInvocationID.x;
	Grid.cells[index].count = 0;
	Grid.cells[index].offset = 0;
}

void determineGridCells()
{
    uint index = gl_GlobalInvocationID.x;

	if (!Particles.particles[index].valid)
	{
		return;
	}

	ivec3 partGridPos = particleGridPos(Particles.particles[index].pos);
	
	if (gridPosValidation(partGridPos))
	{
		int partGridIndex = particleGridIndex(partGridPos);
		atomicAdd(Grid.cells[partGridIndex].count, 1);
	}
}

void countGridCellsOffset()
{
	int currentOffset = 0;
	for (int z = 0; z < Fluid.gridDimentions.z; ++z)
	{
		for (int y = 0; y < Fluid.gridDimentions.y; ++y)
		{
			for (int x = 0; x < Fluid.gridDimentions.x; ++x)
			{
				int gridIndex = particleGridIndex(ivec3(x, y, z));
				Grid.cells[gridIndex].offset = currentOffset;
				currentOffset += Grid.cells[gridIndex].count;
			}
		}
	}
}

void distributeByCells()
{
	uint index = gl_GlobalInvocationID.x;
	
	ivec3 partGridPos = particleGridPos(Particles.particles[index].pos);
	
	if (gridPosValidation(partGridPos))
	{
		int partGridIndex = particleGridIndex(partGridPos);
		int newParticleIndex = atomicAdd(Grid.cells[partGridIndex].offset, 1);
		ParticlesCopy.particles[newParticleIndex] = Particles.particles[index];
		ParticlesCopy.particles[index].gridCellIndex = partGridIndex;
	}
	else
	{
		atomicAdd(Fluid.particlesCount, -1);
	}
}

void moveParticles()
{
    uint index = gl_GlobalInvocationID.x;
	
	ivec3 partGridPos = particleGridPos(ParticlesCopy.particles[index].pos);

	if (!ParticlesCopy.particles[index].valid)
	{
		return;
	}

	ParticlesCopy.particles[index].pos.z += 0.002;
}
