#version 450

struct Particle
{
	int index;
	vec3 pos;
	vec3 velocity;
	int state;
	int gridCellIndex;
};

struct GridCell
{
	int count;
	int offset;
	int offsetBucket;
};

layout(binding = 0) buffer FluidUniform
{
	int particlesCount;
	float gridCellSize;
	ivec3 gridDimentions;
	vec3 gridSize;
} Fluid;

layout(binding = 1) buffer ParticlesStorage
{
	Particle particles[];
} Particles;

layout(binding = 2) buffer ParticlesStorageCopy
{
	Particle particles[];
} ParticlesCopy;

layout(binding = 3) buffer GridStorage
{
	GridCell cells[];
} Grid;

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

ivec3 particleGridPos(vec3 pos)
{
	vec3 shiftFromCenter = Fluid.gridDimentions * Fluid.gridCellSize / 2;
	vec3 particlePosInGrid = (pos + shiftFromCenter) / Fluid.gridCellSize;
	ivec3 partGridPos = ivec3(floor(particlePosInGrid));
	return partGridPos;
}

int particleGridIndex(ivec3 partGridPos)
{
	int partGridIndex = partGridPos.x
		+ partGridPos.y * Fluid.gridDimentions.x
		+ partGridPos.z * Fluid.gridDimentions.x * Fluid.gridDimentions.y;
	return partGridIndex;
}

bool gridPosValidation(ivec3 particleGridPos)
{
	if (particleGridPos.x < 0 || particleGridPos.x >= Fluid.gridDimentions.x)
	{
		return false;
	}
	if (particleGridPos.y < 0 || particleGridPos.y >= Fluid.gridDimentions.y)
	{
		return false;
	}
	if (particleGridPos.z < 0 || particleGridPos.z >= Fluid.gridDimentions.z)
	{
		return false;
	}
	return true;
}

void clearGrid()
{
	uint index = gl_GlobalInvocationID.x;
	Grid.cells[index].count = 0;
	Grid.cells[index].offset = 0;
}

void determineGridCells()
{
	uint index = gl_GlobalInvocationID.x;

	if (Particles.particles[index].state == 0)
	{
		return;
	}

	ivec3 partGridPos = particleGridPos(Particles.particles[index].pos);
	
	if (gridPosValidation(partGridPos))
	{
		int partGridIndex = particleGridIndex(partGridPos);
		atomicAdd(Grid.cells[partGridIndex].count, 1);
	}
}

void countGridCellsOffset()
{
	int currentOffset = 0;
	for (int z = 0; z < Fluid.gridDimentions.z; ++z)
	{
		for (int y = 0; y < Fluid.gridDimentions.y; ++y)
		{
			for (int x = 0; x < Fluid.gridDimentions.x; ++x)
			{
				int gridIndex = particleGridIndex(ivec3(x, y, z));
				Grid.cells[gridIndex].offset = currentOffset;
				Grid.cells[gridIndex].offsetBucket = currentOffset;
				currentOffset += Grid.cells[gridIndex].count;
			}
		}
	}
}

void distributeByCells()
{
	uint index = gl_GlobalInvocationID.x;

	if (Particles.particles[index].state == 0)
	{
		atomicAdd(Fluid.particlesCount, -1);
		return;
	}

	ivec3 partGridPos = particleGridPos(Particles.particles[index].pos);

	if (gridPosValidation(partGridPos))
	{
		int partGridIndex = particleGridIndex(partGridPos);
		int newParticleIndex = atomicAdd(Grid.cells[partGridIndex].offsetBucket, 1);
		ParticlesCopy.particles[newParticleIndex] = Particles.particles[index];
		ParticlesCopy.particles[index].gridCellIndex = partGridIndex;
	}
	else
	{
		atomicAdd(Fluid.particlesCount, -1);
	}
}

void accumulateVelocities()
{
	uint index = gl_GlobalInvocationID.x;
	ivec3 partGridPos = particleGridPos(ParticlesCopy.particles[index].pos);
	ivec3 rangeFrom = clamp(partGridPos - ivec3(1, 1, 1), ivec3(0, 0, 0), Fluid.gridDimentions);
	ivec3 rangeTo = clamp(partGridPos + ivec3(2, 2, 2), ivec3(0, 0, 0), Fluid.gridDimentions);

	for (int z = rangeFrom.z; z < rangeTo.z; ++z)
	{
		for (int y = rangeFrom.y; y < rangeTo.y; ++y)
		{
			for (int x = rangeFrom.x; x < rangeTo.x; ++x)
			{
				int gridCellIndex = particleGridIndex(ivec3(x, y, z));
				GridCell gridCell = Grid.cells[gridCellIndex];

				for (int i = gridCell.offset; i < gridCell.offset + gridCell.count; ++i)
				{
					float dist = (ParticlesCopy.particles[i].pos - ParticlesCopy.particles[index].pos).length();

					if (dist > 1)
					{
						vec3 vector = (ParticlesCopy.particles[i].pos - ParticlesCopy.particles[index].pos) / dist;
						float pressure = 1 - dist / 0.5;
						ParticlesCopy.particles[index].velocity -= vector * pressure / 2000000;
					}
				}
			}
		}
	}
}

void moveParticles()
{
	uint index = gl_GlobalInvocationID.x;

	ParticlesCopy.particles[index].pos += ParticlesCopy.particles[index].velocity;
}